// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartParkingLot.Infrastructure.Context;

#nullable disable

namespace SmartParkingLot.Infrastructure.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20240928185822_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("SmartParkingLot.Infrastructure.Context.Entities.Devices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<Guid>("DeviceAsignedNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("DeviceAsignedNumber");

                    b.HasKey("Id");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeviceAsignedNumber = new Guid("3e4b4312-ee19-4a1a-8018-78310a9e2985")
                        },
                        new
                        {
                            Id = 2,
                            DeviceAsignedNumber = new Guid("b49e1433-73c5-4e59-9f07-17c80ce15565")
                        });
                });

            modelBuilder.Entity("SmartParkingLot.Infrastructure.Context.Entities.ParkingSpots", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsAvailable");

                    b.HasKey("Id");

                    b.ToTable("ParkingSpots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 2,
                            IsAvailable = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
